input {
  file {
    path => "/logs/api-pulse.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
  }
}

filter {
  mutate {
    convert => {
      "responseTime" => "integer"
      "statusCode"   => "integer"
    }
  }

  # null 체크 추가 + boolean 대신 string으로 변경
  if [statusCode] and [statusCode] >= 500 {
    mutate {
      add_field => { "is_error" => "true" }
    }
  } else {
    mutate {
      add_field => { "is_error" => "false" }
    }
  }

  mutate {
    remove_field => ["@version", "host", "log"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "api-pulse-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}